1.to print the python version

In [1]:
import pandas as p
import numpy as n

p.__version__


'2.3.1'

Read dataframe from csv file

In [2]:
df = p.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')
df

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                     170            3.0       159.0     3413.433759   
1                     130            5.0        97.0     3149.664934   
2                     170            NaN        78.0     3079.038997   
3                     220            4.0         NaN     2542.392402   
4                     210            1.0       140.0     3460.870990   
...                   ...            ...         ...             ...   
9699                  140            5.0       164.0     2981.107371   
9700                  180            NaN       154.0     2439.525729   
9701                  220            2.0       138.0     2583.471318   
9702                  230            4.0       177.0     2905.527390   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year  origin fuel_type         drivetrain  \
0             17.7        2003  Europe  Gasoline    All-wheel drive   
1             17.8        2007     USA  Gasoline  Front-wheel drive   
2             15.1        2018  Europe  Gasoline  Front-wheel drive   
3             20.2        2009     USA    Diesel    All-wheel drive   
4             14.4        2009  Europe  Gasoline    All-wheel drive   
...            ...         ...     ...       ...                ...   
9699          17.3        2013  Europe    Diesel  Front-wheel drive   
9700          15.0        2004     USA  Gasoline    All-wheel drive   
9701          15.1        2008     USA    Diesel    All-wheel drive   
9702          19.4        2011     USA    Diesel  Front-wheel drive   
9703          14.7        2005    Asia    Diesel    All-wheel drive   

      num_doors  fuel_efficiency_mpg  
0           0.0            13.231729  
1           0.0            13.688217  
2           0.0            14.246341  
3           2.0            16.912736  
4           2.0            12.488369  
...         ...                  ...  
9699        NaN            15.101802  
9700        0.0            17.962326  
9701       -1.0            17.186587  
9702        1.0            15.331551  
9703       -1.0            14.884467  

[9704 rows x 11 columns]

2.find the number of rows in the dataframe

In [3]:
df.shape[0]

9704

3.Find the number of unique values in a column (eg fuel_type)

In [4]:
df['fuel_type'].nunique()

2

4.Find number of columns in the dataset that has missing values

In [5]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

5.Find maximum fuel efficiency in the dataset

In [6]:
df['Asia' == df.origin]['fuel_efficiency_mpg'].max()

np.float64(23.759122836520497)

6.1 Find the median value of horsepower column in the dataset.

In [7]:
df['horsepower'].median()

np.float64(149.0)

In [8]:
hp_mode=df['horsepower'].mode()[0]
hp_mode

np.float64(152.0)

6.2 calculate the most frequent value of the same horsepower column, index 0 will pick the first value if there is a tie

In [9]:

df['horsepower']=df['horsepower'].fillna(hp_mode)

df['horsepower'].median()


np.float64(152.0)

7.1 select all cars from Asia

In [10]:
Asia_cars = df[df.origin == 'Asia']
filtered_Asia_cars = Asia_cars[['vehicle_weight', 'model_year']]
Asia_cars_df=filtered_Asia_cars[0:7]
Asia_cars_df

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

7.2 Generate matrix X for Asia cars with fields vehicle_weight and	model_year with only 7 rows
XTX = Result of Matrix multiplication of Transpose of X and X 


In [11]:
X = Asia_cars_df.values
X
XTX = X.T.dot(X)
XTX
XTX_inv = n.linalg.inv(XTX)
XTX_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

7.3 create a array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].

In [12]:
y= n.array ([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])


7.7Multiply  the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

In [13]:
inter_result = XTX_inv.dot(X.T)
w = inter_result.dot(y)
w

array([0.01386421, 0.5049067 ])

7.8 sum of all the elements of the result?

In [14]:
w.sum()

np.float64(0.5187709081074016)